---
final_name: cf-redis
min_cli_version: 1.5.0.pre.1113
blobstore:
  provider: s3
  options:
    endpoint: http://s4.uk.bskyb.com
    bucket_name: concourse-artifacts
    access_key_id: C7JY2306j2lN9QFPGM6o
    secret_access_key: EPAVyyfYNhgZWzHHxFHZcLXZGMSj7tfo6UtsNBvJ
